### ISSUE TITLE
Minor grammar fixes for website

### ISSUE THREAD

**Issue by adamshand** [cchalop1/JustDeploy#2]
Hello,

Cool project, thanks for working on it!

Assuming you aren't a native English speaker, and so offering a few grammar fixes to the front page of the website.  I hope that's helpful. :-)

## Zero config \*\*deployment\*\*
**Allows** you to simply deploy your application without dealing with configuration.

## No vendor \*\*lock in\*\*
~~You can~~ **Deploy your** application on any **server,** you only need **an** ssh connection. It can be a  server **in the** cloud or **at** ~~you~~ home ~~server~~.

## **Light weight**
~~JustDeploy is that it~~ Doesn't install anything **extra** on your server, **only** ~~other than~~ your application. This makes it an ideal choice for small servers with limited resources or development **environments.**

**Comment by cchalop1** [comment]
Hi @adamshand,

Thank you so much for the corrections you made it help me a lot.

I have push a new version of the web site updated.
